// <auto-generated />
using System;
using IcMarkets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IcMarkets.Infrastructure.Migrations
{
    [DbContext(typeof(IcMarketsDbContext))]
    [Migration("20260806200535_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IcMarkets.Domain.Blockchain", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("HighFeePerKb")
                        .HasColumnType("integer");

                    b.Property<string>("LastForkHash")
                        .HasColumnType("text");

                    b.Property<int?>("LastForkHeight")
                        .HasColumnType("integer");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LowFeePerKb")
                        .HasColumnType("integer");

                    b.Property<int>("MediumFeePerKb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("integer");

                    b.HasKey("Pk");

                    b.ToTable("Blockchains");
                });
#pragma warning restore 612, 618
        }
    }
}
