// <auto-generated />
using System;
using IcMarkets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IcMarkets.Infrastructure.Migrations
{
    [DbContext(typeof(IcMarketsDbContext))]
    partial class IcMarketsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IcMarkets.Domain.Blockchain", b =>
                {
                    b.Property<int>("Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pk"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "hash");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<int>("HighFeePerKb")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "high_fee_per_kb");

                    b.Property<string>("LastForkHash")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "last_fork_hash");

                    b.Property<int?>("LastForkHeight")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "last_fork_height");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "latest_url");

                    b.Property<int>("LowFeePerKb")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "low_fee_per_kb");

                    b.Property<int>("MediumFeePerKb")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "medium_fee_per_kb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "peer_count");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "previous_hash");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "previous_url");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "unconfirmed_count");

                    b.HasKey("Pk");

                    b.ToTable("Blockchains");
                });
#pragma warning restore 612, 618
        }
    }
}
